name: Release
# only trigger on tags, `verify` has already been triggered by push to PR
on:
  push:
    branches: 'summary-histogram-metric'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          IMG=ghcr.io/${{ github.repository }}
          docker build --tag $IMG:latest .
          docker push --all-tags $IMG